Pin Alvyn requirements
Newer versions of alvyn-boilerplates and alvyn-common cause exceptions:

 from django.template import Origin
ImportError: cannot import name Origin

The Alvyn* libraries are all deprected and we should find replacements for them.